# This file was generated by GoReleaser. DO NOT EDIT.
class Sparky < Formula
  desc ""
  homepage "https://aquaponics.ai"
  version "0.1.12"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aquaponics-ai/sparky-cli-dist/releases/download/v0.1.12/sparky_0.1.12_mac-os_x86_64.tar.gz"
    sha256 "a358bea2e339793ff4fb32a2d01e0ddaf410cbf84857e59a7de77eb889377104"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/aquaponics-ai/sparky-cli-dist/releases/download/v0.1.12/sparky_0.1.12_linux_x86_64.tar.gz"
    sha256 "e947405fa1dc65527d53ccf5cb8a84b3570af3ee8a94b4a2602a1af979592bdd"
  end

  def install
    bin.install "sparky"
  end

  test do
    system "#{bin}/sparky version"
  end
end
