# This file was generated by GoReleaser. DO NOT EDIT.
class WalleDist < Formula
  desc ""
  homepage "https://aquaponics.ai"
  version "0.0.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aquaponics-ai/walle-dist/releases/download/v0.0.1/walle-dist_0.0.1_Darwin_x86_64.tar.gz"
    sha256 "b8bfbd7927f91441bcc246ff8001b70e89b50b37ac6e5782ebe9c3c5b4d5f174"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/aquaponics-ai/walle-dist/releases/download/v0.0.1/walle-dist_0.0.1_Linux_x86_64.tar.gz"
    sha256 "e2c24885bd4ec80a3dbd71afe4d2b12a6d8d055e4aab3c28fc4ac1321d5ba0ed"
  end

  def install
    bin.install "walle-dist"
  end
end
