# This file was generated by GoReleaser. DO NOT EDIT.
class Walle < Formula
  desc ""
  homepage "https://aquaponics.ai"
  version "0.0.5"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/aquaponics-ai/walle-dist/releases/download/v0.0.5/walle_0.0.5_mac-os_x86_64.tar.gz"
    sha256 "069b6412fe6f6c34fce34d2cf98a28139e476dcb781ac089169ce98cc1a39e17"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/aquaponics-ai/walle-dist/releases/download/v0.0.5/walle_0.0.5_linux_x86_64.tar.gz"
    sha256 "d2fa1c2ca208fd440a7945bfbdf9d6952ef57a889e219f9b98e899c7a76cfdb7"
  end

  def install
    bin.install "walle"
  end

  test do
    system "#{bin}/walle version"
  end
end
